Reading.create! \
	number: "1",
	name: "Ed",
	systolic: "140",
	diastolic: "90"
Reading.create! \
	number: "2",
	name: "Jan",
	systolic: "110",
	diastolic: "70"
Reading.create! \
	number: "3",
	name: "Tim",
	systolic: "120",
	diastolic: "80"